build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
labels:
  org.opencontainers.image.title: "ADB Device Manager"
  org.opencontainers.image.description: "Manage Android devices via ADB with web interface"
  org.opencontainers.image.source: "https://github.com/yourusername/adb-device-manager"
  org.opencontainers.image.licenses: "MIT"
args:
  PYTHON_VERSION: "3.11"
