name: ADB Device Manager
version: 1.0.0
slug: adb_device_manager
description: Manage Android devices via ADB with web interface, screen automation, and paperwork generation
url: https://github.com/yourusername/adb-device-manager
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: application
boot: auto
ports:
  5020/tcp: null
ports_description:
  5020/tcp: Web interface (not needed if using Ingress)
ingress: true
ingress_port: 5020
panel_icon: mdi:android-debug-bridge
panel_title: ADB Manager
host_network: true
options:
  devices:
    - ip: "10.10.254.62"
      port: "5555"
      name: "Device 1"
    - ip: "10.10.254.13"
      port: "5555"
      name: "Device 2"
  app_package: "com.bca.bcatrack"
  auto_refresh_enabled: false
  auto_refresh_interval_minutes: 10
  log_level: "info"
schema:
  devices:
    - ip: str
      port: str
      name: str
  app_package: str?
  auto_refresh_enabled: bool?
  auto_refresh_interval_minutes: int?
  log_level: list(debug|info|warning|error)?
